#!/bin/bash
#
# converts a directory with text files into an AMB book
# Mateusz Viste, 2025
#
# requirements:
#
# AMBPACK
# BASH
# EXPAND
# FOLD
# MVCOMP
# SED
#

set -e

SRCDIR="$1"

# title is all uppercase
TITLE="${1^^} DOCUMENTATION"

if [ "x$1" = "x" ] ; then
echo "This script converts a directory with text files into an AMB book."
echo ""
echo "usage: dir2amb.sh dirname"
exit 1
fi

DSTDIR="tempdir"

if [ -f "$SRCDIR".amb ] ; then
echo "$SRCDIR.amb already exists"
exit 1
fi

mkdir "$DSTDIR"
cp "$SRCDIR"/* "$DSTDIR"/

# convert all files to AMC (word-wrap + escape chars + compress)
cd "$DSTDIR"

echo "" > ../index.ama
echo "[ %h$TITLE%t ]" >> ../index.ama
echo "" >> ../index.ama

for f in * ; do

# get the filename without extension
FNAME=${f%.*}

echo "* %l$FNAME:$f" >> ../index.ama

# trim trailing spaces, replace TABs with spaces, word-wrap at 78 characters
# and escape all '%'
cat "$f" | expand | fold -w 78 -s | sed 's/[[:space:]]\+$//' | sed 's/%/%%/g' | dos2unix > "$FNAME".ama

# compress
mvcomp "$FNAME".ama "$FNAME".amc
rm "$FNAME".ama
rm "$f"

done

echo "$TITLE" > title

echo "" >> ../index.ama
echo "%bGenerated by dir2amb.sh" >> ../index.ama

mvcomp ../index.ama index.amc
rm ../index.ama

cd ..

# pack everything up

ambpack c "$DSTDIR" "$SRCDIR".amb


# clean up
rm "$DSTDIR"/*
rmdir "$DSTDIR"

exit 0
