all: .symbolic
	echo Run wmake clean to clean the tree

clean: .symbolic
	rm -f tests/hello/*.com
	rm -f tests/hello/*.exe
	rm -f tests/hello/*.obj
	rm -f tests/hello/*.map
	rm -f tests/minimal/*.com
	rm -f tests/minimal/*.exe
	rm -f tests/minimal/*.obj
	rm -f tests/minimal/*.map
	rm -f tests/stkchk/*.com
	rm -f tests/stkchk/*.exe
	rm -f tests/stkchk/*.obj
	rm -f tests/stkchk/*.map
