# Watcom Makefile to clean the tree

all: .symbolic
	echo Run wmake clean to clean the tree

clean: .symbolic
	rm -f tests/argv/*.com
	rm -f tests/argv/*.exe
	rm -f tests/argv/*.obj
	rm -f tests/argv/*.map
	rm -f tests/hello/*.com
	rm -f tests/hello/*.exe
	rm -f tests/hello/*.obj
	rm -f tests/hello/*.map
	rm -f tests/minimal/*.com
	rm -f tests/minimal/*.exe
	rm -f tests/minimal/*.obj
	rm -f tests/minimal/*.map
	rm -f tests/nullcall/*.exe
	rm -f tests/nullcall/*.obj
	rm -f tests/nullcall/*.map
	rm -f tests/stkchk/*.com
	rm -f tests/stkchk/*.exe
	rm -f tests/stkchk/*.obj
	rm -f tests/stkchk/*.map
